name: Lint GitHub Actions workflows
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        uses: raven-actions/actionlint@v1
        with:
          flags: "-ignore SC2086 -ignore SC2116"
