name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          token: ${{ github.token }}

      - name: Clone main repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Merge main back to develop
        if: ${{ steps.release.outputs.release_created }}
        uses: robotology/gh-action-nightly-merge@v1.4.0
        with:
          stable_branch: 'main'
          development_branch: 'develop'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
