name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          token: ${{ github.token }}

      - name: Clone main repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Create merge branch: main --> develop'
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git checkout release/merge-main-into-develop || git checkout -b release/merge-main-into-develop
          git rebase main
          git push --set-upstream origin release/merge-main-into-develop --force

      - name: Create PR
        if: ${{ steps.release.outputs.release_created }}
        run: |
          (gh pr --repo $GITHUB_REPOSITORY create --fill --title "chore(main): Merge changes from main into develop" --base develop) || exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for the PR
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pull_request_url=$(gh pr view release/merge-main-into-develop --json url --jq '. | .url')
          gh pr --repo $GITHUB_REPOSITORY merge $pull_request_url --auto --merge
          gh pr --repo $GITHUB_REPOSITORY review $pull_request_url --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
